### ISSUE TITLE
Will it support Slim 3

### ISSUE THREAD

**Issue by terrylinooo** [fidelisrafael/slim-mvc#2]
I try to modify this project to Slim 3, but Slim 3 uses a lot dependency injection, and doesn't provide getInstance() anymore.

No idea how to make it work on Slim 3

**Comment by fidelisrafael** [comment]
Hi there, sorry for just replying this now.... 
Hmmm, I don't know about this new version of Slim.... Maybe we can try to make it compatible together... I will take a more detailed look in this later! 🙋

**Comment by fidelisrafael** [comment]
I'm closing this since there is no response and I can't make it work with Slim3 because I'm not working with PHP for a long time now if someone wants to make it compatible just create a PR or another issue to discuss this.
